### ISSUE TITLE
Can't add dependency to Android Gradle project

### ISSUE THREAD

**Issue by SammyO** [Articdive/JNoise#2]
### What is the current behavior?
After following instructions and adding
```
    repositories {
        google()
        mavenCentral()

        maven { url "https://s01.oss.sonatype.org/content/repositories/snapshots/" }
    }
```
to project's build file, and 
```
implementation "de.articdive:jnoise-pipeline:3.0.2"
```
to dependencies in module's build file, I get error message `Failed to resolve: de.articdive:jnoise-pipeline:3.0.2`

### What is the expected behavior?
Dependency is successfully resolved and found.

### What operating system and java version is being used?
Android Studio Artic Fox (Patch 4), Gradle 7.0.4

**Comment by SammyO** [comment]
I went through the commit of version 3.0.2 and saw that the documentation was changed. Following that, I changed the dependency to `implementation "de.articdive:jnoise:3.0.2"`, which worked.

However, I now have problems with Java versions. Is this library compiled with Java 17? If so, that's not supported by Android Studio, as I'm now getting an error `[Unsupported class file major version 61](https://stackoverflow.com/questions/70632741/android-studio-error-unsupported-class-file-major-version-61)`. 

(see https://stackoverflow.com/questions/70632741/android-studio-error-unsupported-class-file-major-version-61)

**Comment by Articdive** [comment]
Yes JNoise is developed on Java 17 because of some changes to strict floating point arithmetic. (the old keyword strictfp in Java 11 and lower). If you'd like however, I believe I could release a Java 11 version of JNoise 4.0.0, which will be what is documented on 'main' and actually somewhat well documented.

**Comment by SammyO** [comment]
Thanks for your answer. After doing some research, I don't think Android Studio can be used with anything higher than Java 11. It would be great if you could release a Java 11 version of your library :)

**Comment by Articdive** [comment]
> Thanks for your answer. After doing some research, I don't think Android Studio can be used with anything higher than Java 11. It would be great if you could release a Java 11 version of your library :)

Alright, give me some time until this weekend and then I'll have it released, promise.

**Comment by Articdive** [comment]
So there is now a jdk-11 artifact available in sonatype snapshots

https://s01.oss.sonatype.org/content/repositories/snapshots/de/articdive/jnoise-pipeline/4.0.0-jdk11-SNAPSHOT/

I will not be making an official release for it (it won't go to maven central), but I will keep it up to date on sonatype snapshots.
