### ISSUE TITLE
Licensing concerns

### ISSUE THREAD

**Issue by Geolykt** [Articdive/JNoise#7]
I've been made aware that the project is licensed under the GPL according to the README.md and the CONTIBUTING.md, but is licensed as MIT judging from the LICENSE file. Given the nature of the GPL and the fact that this is meant to be used as a library this is extremely worrying.

**Comment by Articdive** [comment]
The project is licensed under the MIT License, the reference to GPL is a copy paste error from some other projects and has been corrected in a commit several minutes ago.

The license shipped with the project and specified in maven artifacts is the MIT License.

Sorry about that :).
